// Generated by https://quicktype.io

export interface DB {
    monsters: Monster[];
}

export interface Monster {
    id:                 number;
    numberOfLevel:      number[];
    name:               string;
    level:              number[];
    life:               number[];
    pa:                 number[];
    pm:                 number[];
    xp:                 number[];
    init:               number[];
    strength:           number[];
    fire:               number[];
    water:              number[];
    wind:               number[];
    dodgeAp:            number[];
    dodgeMp:            number[];
    resistanceNeutral:  number[];
    resistanceStrength: number[];
    resistanceFire:     number[];
    resistanceWater:    number[];
    resistanceWind:     number[];
}
